/* Automatisch erzeugt mit tools/build_recipe_data.py */
window.RECIPE_CATALOG = [
  {
    "name": "Gyrossuppe",
    "url": "gyrossuppe.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 1,
    "theme": "suppen",
    "image": "images/gyrossuppe.webp",
    "searchText": "1 kg Gyrosfleisch 200 ml Sahne 2 Stk. Zwiebeln 4 Stk. Paprika 1 Pck. Zwiebelsuppe 8 EL Zigeuner-Sauce 100 g Sahne-Schmelzkäse ½ TL Thymian Etwas Salz, Pfeffer",
    "newRank": 1000,
    "portions": 6,
    "weekGroup": "suppe",
    "weekLabel": "Suppe & Gemüse"
  },
  {
    "name": "Rindergulasch",
    "url": "rindergulasch.html",
    "chapter": "Unsere Klassiker",
    "section": "Schmorgerichte",
    "sectionRank": 6,
    "recipeRank": 1,
    "theme": "schmor",
    "image": "images/rindergulasch.webp",
    "searchText": "1,5 kg Rindfleisch 200 g Schweinebauch 5 Stk. Zwiebeln 2 EL Paprikapulver 2 EL Paprikapulver (Geräuchert) 2 TL Kümmelsamen (zerstoßen) 1 TL Pfeffer ½ TL Salz 3 TL Majoran 1 Stk. Lorbeerblatt ½ TL Cayennepfeffer 550 ml Rinderbrühe 3 EL Tomatenmark 3 Stk. Knoblauchzehen",
    "newRank": 1001,
    "portions": 6,
    "weekGroup": "eintopf",
    "weekLabel": "Schmorgericht"
  },
  {
    "name": "Italienische Steakpfanne",
    "url": "italienische-steakpfanne.html",
    "chapter": "Unsere Klassiker",
    "section": "Pfannen- & Hackgerichte",
    "sectionRank": 5,
    "recipeRank": 0,
    "theme": "klassiker",
    "image": "images/italienische-steakpfanne.webp",
    "searchText": "140 g Hähnchenbrustfilet 180 g Rumpsteak 4 S Bacon 8 Stk. Cherrytomaten 150 g Champignons 50 g eingelgte Tomaten 1 Knoblauchzehe 2 Frühlingszwiebeln 1 EL Rosmarinnadeln 1 Schuss Passierte Tomaten",
    "newRank": 1002,
    "portions": 2,
    "weekGroup": "reis",
    "weekLabel": "Reis & Gemüse"
  },
  {
    "name": "Tefteli",
    "url": "tefteli.html",
    "chapter": "Unsere Klassiker",
    "section": "Pfannen- & Hackgerichte",
    "sectionRank": 5,
    "recipeRank": 5,
    "theme": "klassiker",
    "image": "images/tefteli.webp",
    "searchText": "100 g Reis 1 kg Hackfleisch, gemischt 4 Zwiebeln 2 Möhren 200 ml Gemüsebrühe 1 g.EL Speisestärke etwas Tomatenmark etwas Salz, Pfeffer Öl",
    "newRank": 1003,
    "portions": 6,
    "weekGroup": "kartoffel",
    "weekLabel": "Kartoffeln & Fleisch"
  },
  {
    "name": "Rinderrouladen",
    "url": "rinderrouladen.html",
    "chapter": "Unsere Klassiker",
    "section": "Schmorgerichte",
    "sectionRank": 6,
    "recipeRank": 2,
    "theme": "schmor",
    "image": "images/rinderrouladen.webp",
    "searchText": "4 EL Öl 2 EL Butter 3 Stk. Zwiebeln, in Streifen 4 S Rinderrouladenfleisch etwas Salz, Pfeffer 4 EL Senf 8 S Bacon 3 Stk. Gewürzgurken, in Streifen 1 Möhre, gewürfelt 1/2 Knollensellerie, in Würfel 3 Zwiebeln, gewürfelt 1 EL Tomatenmark 1 EL Mehl 200 ml Rotwein 250 ml Gemüsebrühe",
    "newRank": 1004,
    "portions": 2,
    "weekGroup": "kartoffel",
    "weekLabel": "Kartoffeln & Fleisch"
  },
  {
    "name": "Dillgurken",
    "url": "dillgurken.html",
    "chapter": "Was Kleines dazu",
    "section": "Gemüse & Eingelegtes",
    "sectionRank": 1,
    "recipeRank": 0,
    "theme": "beilagen",
    "image": "images/dillgurken.webp",
    "searchText": "3 Stk. Gurken 2 Stk. Rote Paprika 2 Stk. Knoblauchzehen 1 EL Salz 1 EL Dill 2 Pck Salatkrönung Dill Kräuter 4 EL Öl",
    "newRank": 1005
  },
  {
    "name": "Überbackene Brezeln",
    "url": "ueberbackene-brezeln.html",
    "chapter": "Was Kleines dazu",
    "section": "Brot, Buns & Teiggebäck",
    "sectionRank": 2,
    "recipeRank": 1,
    "theme": "beilagen",
    "image": "images/ueberbackene-brezeln.webp",
    "searchText": "6 Stk. Tiefkühlbrezeln 6 S Schinken 6 S Gouda 300 g Kaisergemüse Salz 1 Pck Sauce Hollandaise",
    "newRank": 1006
  },
  {
    "name": "Kartoffelsalat",
    "url": "kartoffelsalat.html",
    "chapter": "Was Kleines dazu",
    "section": "Salate",
    "sectionRank": 0,
    "recipeRank": 0,
    "theme": "beilagen",
    "image": "images/kartoffelsalat-mf.webp",
    "searchText": "900 g Kartoffeln 3 gekochte Eier 300 g Fleischwurst 1 D Möhren + Erbsen 250 ml Mayonnaise etwas Schmand etwas Salz, Pfeffer 1 Zwiebel",
    "newRank": 1007
  },
  {
    "name": "Rahmsoße",
    "url": "rahmsosse.html",
    "chapter": "Das macht den Unterschied",
    "section": "Saucen & Dips",
    "sectionRank": 0,
    "recipeRank": 0,
    "theme": "sossen",
    "image": "images/rahmsosse.webp",
    "searchText": "400 ml Sahne 2 TL Gemüsebrühe Etwas Butter 2 TL Tomatenmark Etwas Salz, Pfeffer 2 geh. TL Mehl 75 ml Kaltes Wasser",
    "newRank": 1008
  },
  {
    "name": "Remoulade",
    "url": "remoulade.html",
    "chapter": "Das macht den Unterschied",
    "section": "Saucen & Dips",
    "sectionRank": 0,
    "recipeRank": 1,
    "theme": "sossen",
    "image": "images/remoulade.webp",
    "searchText": "1 Stk. Ei 1 TL Senf 2 EL Zitronensaft 300 ml Neutrales Öl 2 Stk. Schalotten 50 g Cornichons 2 TL Kapern 2 TL Fein gehackte Petersilie",
    "newRank": 1009
  },
  {
    "name": "Big Mac Sauce",
    "url": "big-mac-sauce.html",
    "chapter": "Das macht den Unterschied",
    "section": "Saucen & Dips",
    "sectionRank": 0,
    "recipeRank": 2,
    "theme": "sossen",
    "image": "images/big-mac-sauce.webp",
    "searchText": "3 Gewürzgurken 1 kleine Zwiebel 150 g Mayonnaise 4 EL French Dressing 1 TL Weißwein Essig 1 TL Zucker 1/2 TL Salz",
    "newRank": 1010
  },
  {
    "name": "Kräuterdressing",
    "url": "kraeuterdressing.html",
    "chapter": "Das macht den Unterschied",
    "section": "Dressings",
    "sectionRank": 1,
    "recipeRank": 0,
    "theme": "sossen",
    "image": "images/kraeuterdressing.webp",
    "searchText": "30 g Petersilie (ohne Stiel) 25 g Dill (ohne Stiel) 1 Zehe Knoblauch 150 ml Olivenöl 200 ml Pflanzenöl 4 EL weißer Balsamico Essig 1 EL Senf Kerngehäuse 1/2 Gurke Kerngehäuse 1 große Tomate 2 TL Honig 2 Tl Salz 1 TL Pfeffer Spritzer 1/2 Limette",
    "newRank": 1011
  },
  {
    "name": "Pluschki",
    "url": "pluschki.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 2,
    "theme": "suesses",
    "image": "images/pluschki.webp",
    "searchText": "Für den Zuckersirup 250 ml Wasser 250 g Zucker Für den Teig 250 ml Milch 2 EL Zucker 1 Würfel Hefe 100 ml Öl 5 Stk. Eier 2 TL Salz 800 g Mehl Zum Bestreichen ca. 250 g Butter",
    "newRank": 1012
  },
  {
    "name": "Donauwelle",
    "url": "donauwelle.html",
    "chapter": "Was Süßes geht immer",
    "section": "Kuchen & Torten",
    "sectionRank": 1,
    "recipeRank": 1,
    "theme": "suesses",
    "image": "images/donauwelle.webp",
    "searchText": "für den Rührteig 2 Gläser Kirschen 250 g weiche Butter 1 Pr Salz 200 g Zucker 2 Pck Vanillinzucker 5 Eier 1 Pck Backpulver 300 g Mehl 200 ml Buttermilch 3 EL Backkakao Für den Pudding 800 ml Milch 120 g Zucker 2 Pck Vanillepuddingpulver 250 g Butter Fürs Topping 300 g Kuvertüre 3 EL Öl",
    "newRank": 1013
  },
  {
    "name": "Schluchttorte",
    "url": "schluchttorte.html",
    "chapter": "Was Süßes geht immer",
    "section": "Kuchen & Torten",
    "sectionRank": 1,
    "recipeRank": 2,
    "theme": "suesses",
    "image": "images/schluchttorte.webp",
    "searchText": "200 g Nutella 12 Stk. Zwieback 200 g Frischkäse 100 g Puderzucker 1 EL Milch 100 g gehackte Mandeln 400 ml Sahne 2 Pck Sahnesteif 2 Pck Vanillinzucker 1 G Kirschen 1 Pck Tortenguss",
    "newRank": 1014
  },
  {
    "name": "Tiramisu",
    "url": "tiramisu.html",
    "chapter": "Was Süßes geht immer",
    "section": "Desserts",
    "sectionRank": 3,
    "recipeRank": 0,
    "theme": "suesses",
    "image": "images/tiramisu.webp",
    "searchText": "100 g Löffelbiskuits 100 ml Kalter Espresso 3 EL Amaretto 5 Stk. Frische Eier 500 g Mascarpone 1 Stk. Orangensaft 100 g Zucker 2 EL Kakaopulver",
    "newRank": 1015
  },
  {
    "name": "Lemon Curd Tiramisu",
    "url": "lemon-curd-tiramisu.html",
    "chapter": "Was Süßes geht immer",
    "section": "Desserts",
    "sectionRank": 3,
    "recipeRank": 1,
    "theme": "suesses",
    "image": "images/lemon-curd-tiramisu.webp",
    "searchText": "Lemon Curd 2 Stk. Eier (L) 2 Stk. Eigelb 1 Prise Salz 100 g Zucker 2 Stk. Zitronenabrieb 100 g Zitronensaft 80 g Kalte Butter Creme & Schichten 250 g Mascarpone 200 g Sahne 230 g Lemon Curd 1 Pck. Löffelbiskuits Zitronensirup 70 g Zitronensaft 50 g Puderzucker 50 g Limoncello",
    "newRank": 1016
  },
  {
    "name": "Pick Up Dessert",
    "url": "pick-up-dessert.html",
    "chapter": "Was Süßes geht immer",
    "section": "Desserts",
    "sectionRank": 3,
    "recipeRank": 2,
    "theme": "suesses",
    "image": "images/pick-up-dessert.webp",
    "searchText": "500 g Quark 397 g Gekochte gezuckerte Kondensmilch 400 g Sahne 2 Pck. Sahnesteif 10 Stk. Pick Up Riegel 500 g Erdbeeren 500 g Heidelbeeren",
    "newRank": 1017
  },
  {
    "name": "Trauben Mascarpone Becher",
    "url": "trauben-mascarpone-becher.html",
    "chapter": "Was Süßes geht immer",
    "section": "Desserts",
    "sectionRank": 3,
    "recipeRank": 3,
    "theme": "suesses",
    "image": "images/trauben-mascarpone-becher.webp",
    "searchText": "80 g Amarettini 375 g Kernlose grüne Weintrauben 100 g Mascarpone 250 g Frischkäse 5–6 EL Milch 2 EL Zucker ½ Zitronenabrieb 2 EL Zitronensaft 75 g Schlagsahne",
    "newRank": 1018
  },
  {
    "name": "Crème brûlée",
    "url": "creme-brulee.html",
    "chapter": "Was Süßes geht immer",
    "section": "Desserts",
    "sectionRank": 3,
    "recipeRank": 4,
    "theme": "suesses",
    "image": "images/creme-brulee.webp",
    "searchText": "400 ml Sahne 140 ml Vollmilch 85 g Brauner Zucker 5 Stk. Eigelb 1 Stk. Vanilleschote, davon das Mark Zitronenabrieb Weißer Zucker",
    "newRank": 1019
  },
  {
    "name": "Orangencreme",
    "url": "orangencreme.html",
    "chapter": "Was Süßes geht immer",
    "section": "Desserts",
    "sectionRank": 3,
    "recipeRank": 5,
    "theme": "suesses",
    "image": "images/orangencreme.webp",
    "searchText": "700 ml Orangensaft 2 Pck Vanillepuddingpulver 150 g Zucker 200 g Sahne 250 g Mascarpone 2 Pck Vanillinzucker 2 TL Orangenabrieb",
    "newRank": 1020
  },
  {
    "name": "Lebkuchenwürfel",
    "url": "lebkuchenwuerfel.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 9,
    "theme": "suesses",
    "image": "images/pfefferkuchen.webp",
    "searchText": "Für den Teig 250 g Honig 250 g Zucker 150 g Butter 850 - 1000 g Mehl 4 Eier 100 g geriebene Mandeln 100 g Zitronat 1 Pck Hayma Neunerlei Gewürz Für die Füllung 250 g Puderzucker 100 g Kakao 200 g geriebene Haselnüsse 20 g Palmin (Kokosfett) ca. 200 ml Milch",
    "newRank": 1021
  },
  {
    "name": "Currywurst Sauce",
    "url": "currywurst-sauce.html",
    "chapter": "Das macht den Unterschied",
    "section": "Saucen & Dips",
    "sectionRank": 0,
    "recipeRank": 3,
    "theme": "sossen",
    "image": "images/currywurst-sauce.webp",
    "searchText": "2 kg Dosentomaten 500 g Zwiebeln 3 Knoblauchzehen 2-4 EL Olivenöl 50 g brauner Zucker 75 ml Apfelessig Gewürze 200 g Tomatenmark 1/2 gepresste Zitrone 2 TL Salz 1 EL Paprika edelsüß 1 TL Ingwer 1 EL Senfkörner 1 Stk. Sternanis 1/4 TL Zimt 1/2 TL Piment 1/2 TL schwarzer Pfeffer 1 Chilischote 1 EL Worcestershire Sauce 1 TL Curry Pulver",
    "newRank": 1022
  },
  {
    "name": "Rustikaler Schichtsalat mit Speck",
    "url": "rustikaler-schichtsalat-mit-speck.html",
    "chapter": "Was Kleines dazu",
    "section": "Salate",
    "sectionRank": 0,
    "recipeRank": 1,
    "theme": "beilagen",
    "image": "images/schichtsalat-gifhorn.webp",
    "searchText": "1 Kopf Eisbergsalat 1 Stange Sellerie aus dem Glas 1 Bund Schnittlauch 1 Tasse Schinkenwürfel 300 g Erbsen, tiefgekühlt 1 Paprika, grün 750 g Miracle Whip 1-2 TL Zucker 6 Eier 250 g Käse, gerieben 250 g Schinkenspeck",
    "newRank": 1023
  },
  {
    "name": "Lasagne",
    "url": "lasagne.html",
    "chapter": "Unsere Klassiker",
    "section": "Ofengerichte",
    "sectionRank": 7,
    "recipeRank": 2,
    "theme": "pasta",
    "image": "images/lasagne.webp",
    "searchText": "200 g Möhren 200 g Knollensellerie 1 Zwiebel 75 g durchwachsener Speck 1 D Tomaten 3 EL Olivenöl 400 g Rinderhackfleisch (oder gemischtes Hack) 70 g Tomatenmark etwas Salz, Pfeffer 1 TL Kräuter der Provence 60 g Butter 60 g Mehl 500 ml klare Brühe 250 ml Milch 250 ml Sahne 150 g Parmesan, gerieben etwas Muskatnuss, gerieben 9 Lasagneplatten",
    "newRank": 1024,
    "portions": 6,
    "weekGroup": "nudel",
    "weekLabel": "Nudeln & Gemüse"
  },
  {
    "name": "Mandelrollen",
    "url": "mandelrollen.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 3,
    "theme": "suesses",
    "image": "images/mandelrollen.webp",
    "searchText": "450 g Blätterteig-Rechtecke, tiefgekühlt 1 G Kirschen 10 g Speisestärke 1 EL Zucker 100 g Mandelblättchen 1 EL Puderzucker",
    "newRank": 1025
  },
  {
    "name": "Porree-Torte mit Cabanossi",
    "url": "porree-torte-mit-cabanossi.html",
    "chapter": "Unsere Klassiker",
    "section": "Ofengerichte",
    "sectionRank": 7,
    "recipeRank": 3,
    "theme": "klassiker",
    "image": "images/porree-torte.webp",
    "searchText": "1 kg Porree (Lauch) 3 Zwiebeln 250 g Cabanossi 1 EL Butter etwas Salz, Pfeffer etwas Muskat 2-3 EL Paniermehl 230 g Blätterteig 200 g Schmelzkäsescheiben 4 Eier 2 EL Mehl 250 g Schmand 125 g Parmesan, gerieben",
    "newRank": 1026,
    "portions": 6,
    "weekGroup": "teig",
    "weekLabel": "Herzhafter Kuchen"
  },
  {
    "name": "Buttermilchkuchen",
    "url": "buttermilchkuchen.html",
    "chapter": "Was Süßes geht immer",
    "section": "Kuchen & Torten",
    "sectionRank": 1,
    "recipeRank": 4,
    "theme": "suesses",
    "image": "images/buttermilchkuchen.webp",
    "searchText": "250 ml Buttermilch 350 g Mehl 150 g Zucker 3 Eier 1 Pck Vanillezucker 1 1/2 Pck Backpulver 150 g Mandelblättchen 100 g Zucker 200 ml Sahne",
    "newRank": 1027
  },
  {
    "name": "Hähnchen auf chinesische Art",
    "url": "haehnchen-auf-chinesische-art.html",
    "chapter": "Unsere Klassiker",
    "section": "Pfannen- & Hackgerichte",
    "sectionRank": 5,
    "recipeRank": 1,
    "theme": "klassiker",
    "image": "images/hähnchen-chinaart.webp",
    "searchText": "2-3 Hähnchenschenkel ohne Knochen etwas Wasser Eiswürfel + kaltes Wasser (für das Eisbad) Sesamöl 1 EL helle Sojasoße 1 EL Frühlingszwiebel, fein gehackt 1/2 EL frischer Ingwer, fein gehackt 1/2 TL Salz",
    "newRank": 1028,
    "portions": 4,
    "weekGroup": "reis",
    "weekLabel": "Reis & Gemüse"
  },
  {
    "name": "Linsensuppe mit Kassler",
    "url": "linsensuppe-mit-kassler.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 7,
    "theme": "suppen",
    "image": "images/linsensuppe.webp",
    "searchText": "1 Zwiebel 100 g durchwachsener Räucherspeck, gewürfelt 250 g Kassler 1 Lorbeerblatt 1000 ml Fleischbrühe 250 g Linsen etwas Salz, Pfeffer Zucker Essig Bohnenkraut Thymian 6 Kartoffeln 1 Bund Suppengrün",
    "newRank": 1029,
    "portions": 6,
    "weekGroup": "suppe",
    "weekLabel": "Suppe & Fleisch"
  },
  {
    "name": "Eintopf",
    "url": "eintopf.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 6,
    "theme": "suppen",
    "image": "images/eintopf.webp",
    "searchText": "8-10 Kartoffeln 3 Zwiebeln 5 Möhren 4 Stk. Mettenden 2 Lorbeerblätter etwas Salz, Pfeffer Gemüsebrühe Wasser",
    "newRank": 1030,
    "portions": 6,
    "weekGroup": "eintopf",
    "weekLabel": "Eintopf"
  },
  {
    "name": "Rindfleischsuppe mit Gurken",
    "url": "rindfleischsuppe-mit-gurken.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 8,
    "theme": "suppen",
    "image": "images/rindfleischsuppe.webp",
    "searchText": "2500 ml Wasser 800 g Rindfleisch aus der Hüfte Salz paar Pfefferkörner 1 Lorbeerblatt 2 Gewürznelken 1 Stange Porree 400 g Knollensellerie 3-4 Möhren 4 Kartoffeln 6-8 mittelgroße Gewürzgurken",
    "newRank": 1031,
    "portions": 8,
    "weekGroup": "suppe",
    "weekLabel": "Suppe & Gemüse"
  },
  {
    "name": "Couscous-Hack-Pfanne",
    "url": "couscous-hack-pfanne.html",
    "chapter": "Unsere Klassiker",
    "section": "Pfannen- & Hackgerichte",
    "sectionRank": 5,
    "recipeRank": 3,
    "theme": "klassiker",
    "image": "images/couscous-hack-pfanne.webp",
    "searchText": "1 rote Paprikaschote 150 g Champignons 1 kleine Aubergine, ca. 200 g 1/2 Bund glatte Petersilie 400 g gemischtes Hackfleisch 150 g Couscous 200 g griechischer Sahnejoghurt 5 EL Olivenöl Salz Pfeffer 200 ml Gemüsebrühe gemahlener Kreuzkümmel",
    "newRank": 1032,
    "portions": 4,
    "weekGroup": "couscous",
    "weekLabel": "Couscous & Gemüse"
  },
  {
    "name": "Bobat",
    "url": "bobat.html",
    "chapter": "Was Kleines dazu",
    "section": "Herzhafte Kleinigkeiten",
    "sectionRank": 3,
    "recipeRank": 0,
    "theme": "beilagen",
    "image": "images/bobat.webp",
    "searchText": "500 ml Milch 1 Pck Hefe 2 TL Salz 1 TL Zucker 1 Ei 100 ml Öl 750 g Mehl Speckstreifen, Cabanossi oder Mettwurst geriebener Käse",
    "newRank": 1033
  },
  {
    "name": "Rollkuchen",
    "url": "rollkuchen.html",
    "chapter": "Was Kleines dazu",
    "section": "Brot, Buns & Teiggebäck",
    "sectionRank": 2,
    "recipeRank": 3,
    "theme": "beilagen",
    "image": "images/rollkuchen.webp",
    "searchText": "500 ml Dickmilch 400 g Schmand 2 Eier Salz 2 Pck Backpulver 1 kg Mehl, nach Bedarf etwas mehr",
    "newRank": 1034
  },
  {
    "name": "Brisket aus dem Smoker",
    "url": "brisket-aus-dem-smoker.html",
    "chapter": "Unsere Klassiker",
    "section": "Grill & BBQ",
    "sectionRank": 2,
    "recipeRank": 0,
    "theme": "grill",
    "image": "images/brisket-aus-dem-smoker.webp",
    "searchText": "2–3 kg Rinderbrust am Stück 6 EL Sonnenblumenöl 2 EL Meersalz 2 EL Rohrzucker 2 EL Paprikapulver, edelsüß 2 EL Chilipulver 2 EL Schwarzer Pfeffer, frisch gemahlen 2 EL Zwiebelpulver 2 EL Knoblauchpulver 1 Handvoll Räucherchips 1 Smoker oder verschließbarer Grill 1 Grillthermometer 1 Scharfes Messer",
    "newRank": 0,
    "portions": 4,
    "weekGroup": "grill",
    "weekLabel": "Grill & BBQ"
  },
  {
    "name": "Bratwurst selbst gemacht",
    "url": "bratwurst-selbst-gemacht.html",
    "chapter": "Unsere Klassiker",
    "section": "Grill & BBQ",
    "sectionRank": 2,
    "recipeRank": 1,
    "theme": "grill",
    "image": "images/bratwurst-selbst-gemacht.webp",
    "searchText": "750 g Schweinefleisch aus der Schulter 250 g Bacon 1 Bund Petersilie 2 Chilischoten 1 Knoblauchzehe 1 Bio-Limette 1 Bio-Zitrone 1 Prise Rohrzucker 1 TL Salz Nach Geschmack Schwarzer Pfeffer Ca. 3 m Wurstdarm 1 Fleischwolf 1 Wurstfüllaufsatz oder Wurstfüller 1 Verschließbarer Grill",
    "newRank": 1,
    "portions": 8,
    "weekGroup": "grill",
    "weekLabel": "Grill & BBQ"
  },
  {
    "name": "Pulled Pork Burger",
    "url": "pulled-pork-burger.html",
    "chapter": "Unsere Klassiker",
    "section": "Burger",
    "sectionRank": 3,
    "recipeRank": 1,
    "theme": "burger",
    "image": "images/pulled-pork-burger.webp",
    "searchText": "4 Burger-Buns Ca. 600–800 g fertiges Pulled Pork Ca. 200 g Coleslaw Nach Geschmack Juli's BBQ Sauce Etwas Butter oder Öl für die Brötchen",
    "newRank": 2,
    "portions": 4,
    "weekGroup": "grill",
    "weekLabel": "Burger & BBQ"
  },
  {
    "name": "Pulled Pork aus dem Smoker",
    "url": "pulled-pork-aus-dem-smoker.html",
    "chapter": "Unsere Klassiker",
    "section": "Grill & BBQ",
    "sectionRank": 2,
    "recipeRank": 2,
    "theme": "grill",
    "image": "images/pulled-pork-aus-dem-smoker.webp",
    "searchText": "Für das Fleisch Ca. 3 kg Schweinenacken, möglichst am Stück Etwas Sonnenblumenöl Rub 2 EL Salz 2 EL Paprikapulver, edelsüß 2 EL Zwiebelgranulat 2 EL Knoblauchgranulat 2 EL Rosmarin 1 EL Thymian 1 EL Senfpulver 1 EL Chilipulver 2 EL Brauner Zucker oder Rohrzucker 2 EL Schwarzer Pfeffer, grob gemahlen Außerdem Bis zu 500 ml Juli's BBQ Sauce , nach Geschmack Nach Bedarf Räucherchips",
    "newRank": 3,
    "portions": 10,
    "weekGroup": "grill",
    "weekLabel": "Grill & BBQ"
  },
  {
    "name": "Russischer Zupfkuchen mit Kirschen",
    "url": "russischer-zupfkuchen-mit-kirschen.html",
    "chapter": "Was Süßes geht immer",
    "section": "Kuchen & Torten",
    "sectionRank": 1,
    "recipeRank": 6,
    "theme": "suesses",
    "image": "images/russischer-zupfkuchen-mit-kirschen.webp",
    "searchText": "425 g Weizenmehl 40 g Kakaopulver 3 gestr. TL Backpulver 200 g Zucker 2 Pck. Vanillezucker 2 Eier, Größe M 250 g Butter 1 Prise Salz 250 g Butter 1 kg Magerquark 250 g Zucker 2 Pck. Vanille-Puddingpulver 4 Eier, Größe M 1 Glas Sauerkirschen Etwas Butter zum Einfetten",
    "newRank": 4
  },
  {
    "name": "Lagman",
    "url": "lagman.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 4,
    "theme": "suppen",
    "image": "images/lagman.webp",
    "searchText": "600–700 g Schweinenacken 2 Zwiebeln 2 Zehen Knoblauch 1 Bund Dschusai oder Knoblauch-Schnittlauch 3 Möhren 1 Paprika 1 Rettich 2 EL Tomatenmark Optional 1 Peperoni 400 g Spaghetti oder andere lange Nudeln 2 EL Margarine oder neutrales Öl Nach Bedarf Wasser Nach Geschmack Salz und Pfeffer",
    "newRank": 5,
    "portions": 5,
    "weekGroup": "nudel",
    "weekLabel": "Nudeln & Fleisch"
  },
  {
    "name": "Hühnersuppe",
    "url": "huehnersuppe.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 3,
    "theme": "suppen",
    "image": "images/huehnersuppe.webp",
    "searchText": "1 Suppenhuhn 1 Bund Suppengrün 2 Stangen Sellerie ½ Knolle Ingwer, etwa handflächengroß 1 Zwiebel 2 Zehen Knoblauch Etwas Neutrales Speiseöl Nach Bedarf Wasser 1 Sternanis 15 Pfefferkörner 15 Fenchelsamen 25 Koriandersamen 5 Wacholderbeeren 3 Lorbeerblätter Optional Liebstöckel Nach Geschmack Salz und Pfeffer 1 Karotte 150 g Suppennudeln Nach Bedarf Frühlingslauch, nur der grüne Teil Nach Bedarf Petersilie",
    "newRank": 6,
    "portions": 8,
    "weekGroup": "suppe",
    "weekLabel": "Suppe & Huhn"
  },
  {
    "name": "Rigatoni al Pollo Funghi",
    "url": "rigatoni-al-pollo-funghi.html",
    "chapter": "Unsere Klassiker",
    "section": "Pasta",
    "sectionRank": 0,
    "recipeRank": 4,
    "theme": "pasta",
    "image": "images/rigatoni-al-pollo-funghi.webp",
    "searchText": "400 g Rigatoni 500 g Hähnchenbrustfilet 250 g Kleine Champignons 250 g Kirschtomaten 1 Rote Zwiebel 1 Knoblauchzehe 2 EL Tomatenmark 500 ml Passierte Tomaten Etwas Olivenöl Nach Bedarf Salz und Pfeffer Nach Bedarf Parmesan am Stück",
    "newRank": 7,
    "portions": 4,
    "weekGroup": "nudel",
    "weekLabel": "Pasta"
  },
  {
    "name": "Spaghetti Bolognese",
    "url": "spaghetti-bolognese.html",
    "chapter": "Unsere Klassiker",
    "section": "Pasta",
    "sectionRank": 0,
    "recipeRank": 3,
    "theme": "pasta",
    "image": "images/spaghetti-bolognese.webp",
    "searchText": "400 g Spaghetti, Tagliatelle oder Rigatoni 100 g Pancetta oder Speckwürfel 500 g Rinderhackfleisch 2 Karotten 2 Stangen Sellerie 1 große Zwiebel 2 EL Tomatenmark 100 ml Passierte Tomaten 500 ml Hühnerbrühe 150 ml Rotwein 1 kleiner Schuss Milch, etwa 50 ml Etwas Olivenöl Nach Bedarf Salz und Pfeffer Nach Bedarf Parmesan, frisch gerieben",
    "newRank": 8,
    "portions": 4,
    "weekGroup": "nudel",
    "weekLabel": "Pasta"
  },
  {
    "name": "Zimtschnecken",
    "url": "zimtschnecken.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 4,
    "theme": "suesses",
    "image": "images/zimtschnecken.webp",
    "searchText": "500 g Weißmehl ¾ TL Salz 80 g Zucker 1 Pck. Vanillinzucker 210 ml Milch, lauwarm 1 Ei 21 g Frische Hefe, 1 Päckchen 80 g Butter, zimmerwarm Ca. 40 ml Schlagsahne Etwas Butter für die Form Klassische Zimtfüllung 120 g sehr weiche Butter 200 g brauner Zucker 2–3 TL Zimt, am besten Ceylon-Zimt Butter, braunen Zucker und Zimt zu einer gleichmäßigen, streichfähigen Creme verrühren. Pistazienfüllung 80 g Pistaziencreme Etwas sehr weiche Butter 3 EL brauner Zucker 1 EL Zimt Alle Zutaten gründlich zu einer glatten, streichfähigen Pistaziencreme verrühren. Klassisches Frischkäsefrosting 50 g weiche Butter 60 g Puderzucker 200 g Frischkäse Butter, Puderzucker und Frischkäse glatt und cremig verrühren. Pistazienfrosting 100 g Pistaziencreme 100 g Frischkäse 1 Prise Salz 60 g Puderzucker Pistaziencreme, Frischkäse, Salz und Puderzucker zu einem glatten Frosting verrühren.",
    "newRank": 9
  },
  {
    "name": "Meine Pasta",
    "url": "meine-pasta.html",
    "chapter": "Unsere Klassiker",
    "section": "Pasta",
    "sectionRank": 0,
    "recipeRank": 2,
    "theme": "pasta",
    "image": "images/meine-pasta.webp",
    "searchText": "400 g Rigatoni oder Tagliatelle 1 große Zwiebel 2 Knoblauchzehen 2 EL Olivenöl 2–3 EL Tomatenmark 300 ml Schlagsahne Etwa 100 ml Nudelwasser 60–80 g Parmesan, frisch gerieben 1 TL Paprikapulver, geräuchert Etwas Pfeffer Nach Bedarf Salz",
    "newRank": 10,
    "portions": 4,
    "weekGroup": "nudel",
    "weekLabel": "Pasta"
  },
  {
    "name": "Tagliatelle mit Champignons",
    "url": "tagliatelle-mit-champignons.html",
    "chapter": "Unsere Klassiker",
    "section": "Pasta",
    "sectionRank": 0,
    "recipeRank": 1,
    "theme": "pasta",
    "image": "images/tagliatelle-mit-champignons.webp",
    "searchText": "400 g Tagliatelle 400 g Champignons 400 ml Schlagsahne 1 Schalotte 30 g Butter 100 ml Hühnerbrühe 60 g Parmesan, frisch gerieben ½ Bund Petersilie Nach Geschmack Salz Etwas Nudelwasser",
    "newRank": 11,
    "portions": 4,
    "weekGroup": "nudel",
    "weekLabel": "Pasta"
  },
  {
    "name": "Streuselkuchen mit Kirschen",
    "url": "streuselkuchen-mit-kirschen.html",
    "chapter": "Was Süßes geht immer",
    "section": "Kuchen & Torten",
    "sectionRank": 1,
    "recipeRank": 5,
    "theme": "suesses",
    "image": "images/streuselkuchen-mit-kirschen.webp",
    "searchText": "Für den Hefeteig 450–500 g Mehl 2 Pck. Trockenhefe, alternativ 1 Würfel frische Hefe 1 Ei 150 g Joghurt 120 ml Milch, lauwarm 130 g Butter, zerlassen 150 g Zucker 1 Pck. Vanillezucker Für die Streusel 200 g Butter, weich 300 g Mehl 150 g Zucker 1 Pck. Vanillezucker 1 Prise Salz Außerdem 1 Glas Kirschen 200 ml Schlagsahne",
    "newRank": 12
  },
  {
    "name": "Kartoffelsuppe",
    "url": "kartoffelsuppe.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 2,
    "theme": "suppen",
    "image": "images/kartoffelsuppe.webp",
    "searchText": "1 kg Kartoffeln 4 Karotten 1 Bund Suppengrün 2 EL Gemüsebrühepulver, plus etwas zum Abschmecken Nach Bedarf Wasser 3 Paar Wiener Würstchen Nach Geschmack Salz",
    "newRank": 13,
    "portions": 4,
    "weekGroup": "suppe",
    "weekLabel": "Suppe & Gemüse"
  },
  {
    "name": "Bruschetta Butter",
    "url": "bruschetta-butter.html",
    "chapter": "Das macht den Unterschied",
    "section": "Würzöle & Butter",
    "sectionRank": 3,
    "recipeRank": 1,
    "theme": "sossen",
    "image": "images/bruschetta-butter.webp",
    "searchText": "500 g Butter, zimmerwarm 250 g Cherrytomaten 1 Knolle Knoblauch 2–3 EL Tomatenmark 30 g Parmesan, fein gerieben 3–4 EL Guter Balsamico oder Crema di Balsamico 1 Bund Basilikum, gehackt Nach Geschmack Salz Optional Chiliflocken",
    "newRank": 14
  },
  {
    "name": "Blätterteig-Küchlein mit Vanillecreme",
    "url": "blaetterteig-kuechlein-mit-vanille-mascarpone-creme.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 5,
    "theme": "suesses",
    "image": "images/blaetterteig-kuechlein-mit-vanille-mascarpone-creme.webp",
    "searchText": "Für die Küchlein 2 Rollen Blätterteig aus dem Kühlregal 1 Eigelb Nach Bedarf Mandelblättchen Für die Creme 300 ml Kalte Milch 1 Pck. Paradiescreme Vanille 250 g Mascarpone 100 ml Kalte Schlagsahne 1 Pck. Sahnesteif 1 Pck. Vanillezucker Außerdem Nach Bedarf Puderzucker zum Bestäuben",
    "newRank": 15
  },
  {
    "name": "Cremiges Balsamico-Dressing",
    "url": "cremiges-balsamico-dressing.html",
    "chapter": "Das macht den Unterschied",
    "section": "Dressings",
    "sectionRank": 1,
    "recipeRank": 1,
    "theme": "sossen",
    "image": "images/cremiges-balsamico-dressing.webp",
    "searchText": "200 g Heller Balsamico 250 g Wasser 80–100 g Zucker, je nach gewünschter Süße 20 g Salz 20 g Gemüsebrühepulver, gekörnt 200 g Saure Sahne oder Schmand 300 g Naturjoghurt, 0,1 % Fett 60 g Mittelscharfer Senf 200 g Neutrales Pflanzenöl ¼ TL Schwarzer Pfeffer Nach Belieben Schnittlauch, Petersilie, Thymian, Rosmarin und Basilikum, fein gehackt",
    "newRank": 16
  },
  {
    "name": "Pulled-Kassler-Burger",
    "url": "pulled-kassler-burger.html",
    "chapter": "Unsere Klassiker",
    "section": "Burger",
    "sectionRank": 3,
    "recipeRank": 2,
    "theme": "burger",
    "image": "images/pulled-kassler-burger.webp",
    "searchText": "4 Burger-Buns Ca. 600 g fertiges Pulled Kassler Ca. 200 g Coleslaw Nach Geschmack Juli's BBQ Sauce Etwas Butter oder Öl für die Brötchen",
    "newRank": 17,
    "portions": 4,
    "weekGroup": "grill",
    "weekLabel": "Burger & BBQ"
  },
  {
    "name": "Pulled Kassler",
    "url": "pulled-kassler.html",
    "chapter": "Unsere Klassiker",
    "section": "Grill & BBQ",
    "sectionRank": 2,
    "recipeRank": 3,
    "theme": "grill",
    "image": "images/pulled-kassler.webp",
    "searchText": "2–2,5 kg Kasslernacken ohne Knochen 2 EL Senf 2–3 EL BBQ-Gewürzmischung ohne zusätzliches Salz 3 große Zwiebeln 500 ml Cola 500 ml Kirschsaft; alternativ durch weitere Cola ersetzen Nach Bedarf Juli's BBQ Sauce",
    "newRank": 18,
    "portions": 8,
    "weekGroup": "grill",
    "weekLabel": "Grill & BBQ"
  },
  {
    "name": "Pasta mit Rindfleisch in Sahnesauce",
    "url": "pasta-mit-rindfleisch-in-sahnesauce.html",
    "chapter": "Unsere Klassiker",
    "section": "Pasta",
    "sectionRank": 0,
    "recipeRank": 0,
    "theme": "pasta",
    "image": "images/pasta-mit-rindfleisch-in-sahnesauce.webp",
    "searchText": "400 g Tagliatelle (Bandnudeln), alternativ Rigatoni Rigate 500 g Rinderfiletstreifen 1 Rote Zwiebel 2 Knoblauchzehen 100 g Getrocknete Tomaten in Öl, abgetropft 1 EL Olivenöl 250 ml Sahne Etwas Nudelwasser 50 g Rucola 60 g Parmesan, am Stück Etwas Salz und schwarzer Pfeffer",
    "newRank": 19,
    "portions": 4,
    "weekGroup": "nudel",
    "weekLabel": "Pasta"
  },
  {
    "name": "Frische Pizza",
    "url": "frische-pizza-mit-haehnchen-und-salat.html",
    "chapter": "Unsere Klassiker",
    "section": "Pizza",
    "sectionRank": 4,
    "recipeRank": 1,
    "theme": "pizza",
    "image": "images/frische-pizza.webp",
    "searchText": "Hefeteig 21 g Frische Hefe 220 ml Warmes Wasser ½ TL Zucker 400 g Mehl 1 TL Salz 2 EL Öl Belag 500 g Hähnchenbrustfilet 1½ EL Gyrosgewürz 1½ EL Öl 1 Gemüsezwiebel 200 ml BBQ-Sauce von Kühne oder Juli's BBQ-Sauce ½ Eisbergsalat 1 Gurke 350 g Tomaten 200 g Geriebener Käse Dressing 400 g Schmand 100 g Salatmayonnaise 1 Pck. Dillkräutermischung",
    "newRank": 20,
    "portions": 6,
    "weekGroup": "teig",
    "weekLabel": "Pizza & Salat"
  },
  {
    "name": "Juli's 3-2-1 Ribs",
    "url": "3-2-1-ribs.html",
    "chapter": "Unsere Klassiker",
    "section": "Grill & BBQ",
    "sectionRank": 2,
    "recipeRank": 4,
    "theme": "grill",
    "image": "images/3-2-1-ribs.webp",
    "searchText": "6 Stränge / ca. 3 kg Schweinerippchen, am besten Baby Back Ribs 200 ml Cola oder Apfelsaft; alternativ eine beliebige Flüssigkeit, z. B. Punica Nach Bedarf BBQ-Sauce zum Bestreichen, z. B. Juli's BBQ Sauce Magic Dust Rub 6 EL Paprikapulver, edelsüß 3 EL Brauner Zucker 1½ EL Salz 1½ EL Schwarzer Pfeffer 1½ EL Knoblauchgranulat 1½ EL Zwiebelgranulat 1½ TL Senfpulver 1½ TL Kreuzkümmel 1 TL Cayennepfeffer",
    "newRank": 21,
    "portions": 6,
    "weekGroup": "grill",
    "weekLabel": "Grill & BBQ"
  },
  {
    "name": "Burger-Buns",
    "url": "burger-buns.html",
    "chapter": "Was Kleines dazu",
    "section": "Brot, Buns & Teiggebäck",
    "sectionRank": 2,
    "recipeRank": 2,
    "theme": "beilagen",
    "image": "images/burger-buns.webp",
    "searchText": "Teig 500 g Weizenmehl Type 550 200 ml Lauwarmes Wasser 4 EL Milch 42 g Frische Hefe (1 Würfel) 35 g Zucker 8 g Salz 80 g Weiche Butter 1 Ei Zum Bestreichen 1 Ei 2 EL Milch 2 EL Wasser Etwas Sesam",
    "newRank": 22
  },
  {
    "name": "Guacamole-Cheeseburger mit Nachos",
    "url": "guacamole-cheeseburger-mit-nachos.html",
    "chapter": "Unsere Klassiker",
    "section": "Burger",
    "sectionRank": 3,
    "recipeRank": 0,
    "theme": "burger",
    "image": "images/guacamole-cheeseburger-mit-nachos.webp",
    "searchText": "Für die Burger 600 g Rinderhackfleisch Etwas Salz und Pfeffer für die Pattys 4 Burgerbrötchen 4 Scheiben Cheddar Etwas Nacho-Chips 4 große Blätter Blattsalat 20 g Butter zum Rösten der Brötchen 1 EL Neutrales Öl zum Braten oder Einölen des Grillrosts Für die Guacamole 2 Reife Avocados 1 Limette 1 Tomate 1 kleine Rote Zwiebel 2 Knoblauchzehen 1 Jalapeño oder Chilischote Nach Geschmack Salz und Pfeffer für die Guacamole",
    "newRank": 23,
    "portions": 4,
    "weekGroup": "grill",
    "weekLabel": "Burger & BBQ"
  },
  {
    "name": "Juli's BBQ Sauce",
    "url": "julis-bbq-sauce.html",
    "chapter": "Das macht den Unterschied",
    "section": "Saucen & Dips",
    "sectionRank": 0,
    "recipeRank": 4,
    "theme": "sossen",
    "image": "images/julis-bbq-sauce.webp",
    "searchText": "250 g Zwiebeln 150 g Worcestersauce 3 Knoblauchzehen 150 g Brauner Zucker 500 g Ketchup 1 TL Mittelscharfer Senf 1 TL Paprikapulver, edelsüß 1 TL Paprikapulver, geräuchert 2 TL Chilipulver 4 Spritzer Zitronensaft 1 TL Salz 0,5–1 TL Salz, zusätzlich nach Geschmack 1 EL Sonnenblumenöl",
    "newRank": 24
  },
  {
    "name": "Juli's Schaschlik mit Mayo",
    "url": "julis-schaschlik-mit-mayo.html",
    "chapter": "Unsere Klassiker",
    "section": "Grill & BBQ",
    "sectionRank": 2,
    "recipeRank": 5,
    "theme": "grill",
    "image": "images/julis-marinade-mit-mayo.webp",
    "searchText": "2 kg Schweinenacken 4–5 große Zwiebeln 250 g Mayonnaise 1 EL Senf 2 TL Paprikapulver, edelsüß 1 TL Koriandersaat, gestoßen 1 TL Pfeffer 28 g Salz 2 Knoblauchzehen",
    "newRank": 25,
    "portions": 8,
    "weekGroup": "grill",
    "weekLabel": "Grill & BBQ"
  },
  {
    "name": "Schaschlik mit Zigeunersauce",
    "url": "schaschlik-von-andre.html",
    "chapter": "Unsere Klassiker",
    "section": "Grill & BBQ",
    "sectionRank": 2,
    "recipeRank": 6,
    "theme": "grill",
    "image": "images/schaschlikmarinade.webp",
    "searchText": "5 kg Schweinenacken oder Putenoberkeule 1 kg Zwiebeln, in Halbringen 5–10 Knoblauchzehen 70 g Salz 1,5 TL Pfeffer 1,5 TL Cayennepfeffer 250 ml Sonnenblumenöl 250 ml Mineralwasser mit Kohlensäure 250 ml Zigeunersauce (von Homann oder Knorr) 4–5 Lorbeerblätter",
    "newRank": 26,
    "portions": 20,
    "weekGroup": "grill",
    "weekLabel": "Grill & BBQ"
  },
  {
    "name": "Juli's Marinade mit Mayo",
    "url": "julis-marinade-mit-mayo.html",
    "chapter": "Das macht den Unterschied",
    "section": "Marinaden",
    "sectionRank": 2,
    "recipeRank": 0,
    "theme": "sossen",
    "image": "images/julis-marinade-mit-mayo.webp",
    "searchText": "4–5 große Zwiebeln 250 g Mayonnaise 1 EL Senf 2 TL Paprikapulver, edelsüß 1 TL Koriandersaat, gestoßen 1 TL Pfeffer 28 g Salz 2 Knoblauchzehen",
    "newRank": 27
  },
  {
    "name": "Marinade mit Zigeunersauce",
    "url": "schaschlikmarinade.html",
    "chapter": "Das macht den Unterschied",
    "section": "Marinaden",
    "sectionRank": 2,
    "recipeRank": 1,
    "theme": "sossen",
    "image": "images/schaschlikmarinade.webp",
    "searchText": "1 kg Zwiebeln, in Halbringen 5–10 Knoblauchzehen 70 g Salz 1,5 TL Pfeffer 1,5 TL Cayennepfeffer 250 ml Sonnenblumenöl 250 ml Mineralwasser mit Kohlensäure 250 ml Zigeunersauce (von Homann oder Knorr) 4–5 Lorbeerblätter",
    "newRank": 28
  },
  {
    "name": "Apfel im Schlafrock",
    "url": "apfel-im-schlafrock.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 6,
    "theme": "suesses",
    "image": "images/apfel-im-schlafrock.webp",
    "searchText": "16 Apfelhälften geschält und entkernt Etwas Zitronenwasser 750 g Mehl 375 g Fett 195 g Zucker 3 Stk. Eier",
    "newRank": 29
  },
  {
    "name": "Butterkuchen",
    "url": "butterkuchen-nach-thomas-p-mama.html",
    "chapter": "Was Süßes geht immer",
    "section": "Kuchen & Torten",
    "sectionRank": 1,
    "recipeRank": 3,
    "theme": "suesses",
    "image": "images/butterkuchen-nach-thomas-p-mama.webp",
    "searchText": "500 g Mehl 80 g Butter 75 g Zucker 1 Würfel Hefe 1 TL Salz 250 ml Wasser 250 g Butter für den Belag 250 g Zucker für den Belag Etwas Vanillezucker 3 Stk. Eigelb",
    "newRank": 30
  },
  {
    "name": "Coleslaw",
    "url": "coleslaw.html",
    "chapter": "Was Kleines dazu",
    "section": "Salate",
    "sectionRank": 0,
    "recipeRank": 2,
    "theme": "beilagen",
    "image": "images/coleslaw.webp",
    "searchText": "1 kleiner bis mittelgroßer Kopf Weißkohl 2 Stk. Rote Zwiebeln 4 Stk. Möhren 500 g Salatmayonnaise 70 g Puderzucker 50 ml Sprite 1 EL Essig 1 gestr. TL Salz ½ TL Pfeffer",
    "newRank": 31
  },
  {
    "name": "Frikadellen",
    "url": "frikadellen.html",
    "chapter": "Unsere Klassiker",
    "section": "Pfannen- & Hackgerichte",
    "sectionRank": 5,
    "recipeRank": 4,
    "theme": "klassiker",
    "image": "images/frikadellen.webp",
    "searchText": "1,2 kg Hackfleisch 1 Stk. Ei 100 g Brot, in Milch eingeweicht 200 g Zwiebeln Nach Geschmack Salz und Pfeffer Etwas Öl zum Braten",
    "newRank": 32,
    "portions": 10,
    "weekGroup": "kartoffel",
    "weekLabel": "Fleischgericht"
  },
  {
    "name": "Gefüllte Zucchini",
    "url": "gefuellte-zucchini.html",
    "chapter": "Unsere Klassiker",
    "section": "Ofengerichte",
    "sectionRank": 7,
    "recipeRank": 4,
    "theme": "klassiker",
    "image": "images/gefuellte-zucchini.webp",
    "searchText": "1 Stk. Brötchen vom Vortag 4 mittelgroße Zucchini 1 kleine Zwiebel 1 Bund Petersilie 300 g Gemischtes Hackfleisch 1 Stk. Ei 1 TL Mittelscharfer Senf Etwas Paprikapulver, Muskat, Salz und Pfeffer 1 Stk. Knoblauchzehe 1 kleine Dose Tomaten 1 TL Oregano 100 g Emmentaler, gerieben",
    "newRank": 33,
    "portions": 4,
    "weekGroup": "gemuese",
    "weekLabel": "Gemüse & Fleisch"
  },
  {
    "name": "Guiso",
    "url": "guiso.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 5,
    "theme": "suppen",
    "image": "images/guiso.webp",
    "searchText": "500 g Fleisch 1 Stk. Zwiebel 2 Stk. Paprika Etwas Salz, Pfeffer, Knoblauch und Paprikapulver Etwas Tomatenmark 1 Dose Tomatencremesuppe 500 g Nudeln, z. B. Spätzle Nach Bedarf Wasser",
    "newRank": 34,
    "portions": 4,
    "weekGroup": "nudel",
    "weekLabel": "Nudeln & Fleisch"
  },
  {
    "name": "Gyrospizza vom Blech",
    "url": "gyrospizza-vom-blech.html",
    "chapter": "Unsere Klassiker",
    "section": "Pizza",
    "sectionRank": 4,
    "recipeRank": 2,
    "theme": "pizza",
    "image": "images/gyrospizza-vom-blech.webp",
    "searchText": "600 g Putenbrust 5 große Zwiebeln 4 Stk. Knoblauchzehen 8–9 EL Öl 2–3 TL Gyros-Gewürzsalz 500 g Mehl Etwas Salz, Pfeffer und Zucker 125 ml Milch 1 Würfel Frische Hefe 500 g Stückige Tomaten 1 TL Oregano, getrocknet 200–250 g Emmentaler, gerieben",
    "newRank": 35,
    "portions": 6,
    "weekGroup": "teig",
    "weekLabel": "Ofengericht"
  },
  {
    "name": "Hähnchen-Gemüse-Pfanne",
    "url": "haehnchen-gemuese-pfanne.html",
    "chapter": "Unsere Klassiker",
    "section": "Pfannen- & Hackgerichte",
    "sectionRank": 5,
    "recipeRank": 2,
    "theme": "klassiker",
    "image": "images/haehnchen-gemuese-pfanne.webp",
    "searchText": "500 g Hähnchenfleisch 250 g Spätzle, gekocht 1 Stk. Zwiebel 1 Stk. Zucchini 3 Stk. Tomaten 1 Stk. Paprika 3 EL Hollandaise oder Mayonnaise 200 ml Sahne Nach Wunsch Chilisauce oder andere Sauce",
    "newRank": 36,
    "portions": 4,
    "weekGroup": "nudel",
    "weekLabel": "Gemüse & Spätzle"
  },
  {
    "name": "Hot-Dog-Cake",
    "url": "hot-dog-cake.html",
    "chapter": "Unsere Klassiker",
    "section": "Ofengerichte",
    "sectionRank": 7,
    "recipeRank": 6,
    "theme": "klassiker",
    "image": "images/hot-dog-cake.webp",
    "searchText": "1 Stk. Zwiebel 4 Stk. Gewürzgurken 250 g Gemischtes Hackfleisch 2 Stk. Eier 1 TL Salz Etwas Pfeffer Nach Geschmack Senf 15 Stk. Wiener Würstchen Etwas Röstzwiebeln",
    "newRank": 37,
    "portions": 6,
    "weekGroup": "teig",
    "weekLabel": "Ofengericht"
  },
  {
    "name": "Lieblingsgemüse aus dem Ofen",
    "url": "lenas-lieblingsgemuese-aus-dem-ofen.html",
    "chapter": "Was Kleines dazu",
    "section": "Gemüse & Eingelegtes",
    "sectionRank": 1,
    "recipeRank": 1,
    "theme": "beilagen",
    "image": "images/lenas-lieblingsgemuese-aus-dem-ofen.webp",
    "searchText": "2 Stk. Paprika 1 Stk. Aubergine 1 Stk. Zucchini 200 g Champignons 1 rote Zwiebel 2 Stk. Möhren 2 Stk. Knoblauchzehen 120 ml Olivenöl 3 EL Balsamico 2 EL Italienische Kräuter Etwas Rosmarin, Salz und Pfeffer",
    "newRank": 38
  },
  {
    "name": "Nudelsalat",
    "url": "nudelsalat-nach-melanie-pauls.html",
    "chapter": "Was Kleines dazu",
    "section": "Salate",
    "sectionRank": 0,
    "recipeRank": 3,
    "theme": "beilagen",
    "image": "images/nudelsalat-nach-melanie-pauls.webp",
    "searchText": "250 g Kleine Nudeln 1 Stk. Zwiebel 1 Stk. Paprika 1 Stk. Salatgurke 2–4 Stk. Fleischwurst oder Geflügelwurst 1 Dose Mais 1 Becher Schmand Nach Geschmack Mayonnaise Etwas Salz und Pfeffer",
    "newRank": 39
  },
  {
    "name": "Pikante Streusel-Tarte",
    "url": "pikante-streusel-tarte.html",
    "chapter": "Was Kleines dazu",
    "section": "Herzhafte Kleinigkeiten",
    "sectionRank": 3,
    "recipeRank": 1,
    "theme": "beilagen",
    "image": "images/pikante-streusel-tarte.webp",
    "searchText": "75 g Semmelbrösel 50 g Emmentaler, gerieben 50 g Weiche Butter oder Margarine 150 g Möhren 150 g Frühlingszwiebeln 3 Stk. Eier 100 ml Speiseöl 125 g Crème fraîche Kräuter 150 g Emmentaler, gerieben 1 TL Salz Etwas Pfeffer 180 g Weizenmehl 2½ gestr. TL Backpulver 200 g Cocktailtomaten",
    "newRank": 40
  },
  {
    "name": "Pilz-Curry mit Mandeln",
    "url": "pilz-curry-mit-mandeln.html",
    "chapter": "Unsere Klassiker",
    "section": "Pfannen- & Hackgerichte",
    "sectionRank": 5,
    "recipeRank": 7,
    "theme": "klassiker",
    "image": "images/pilz-curry-mit-mandeln.webp",
    "searchText": "300–400 g Weiße Champignons 300–400 g Braune Champignons 200 g Shiitake-Pilze 1 mittelgroße Zwiebel 1 mittelgroße Möhre 3 EL Mandeln ohne Haut 2–3 EL Öl Etwas Salz und Pfeffer 2–3 EL Curry 1 gehäufter EL Mehl 300 ml Milch 2 TL Gemüsebrühe 100 g TK-Erbsen 3–4 Stiele Petersilie",
    "newRank": 41,
    "portions": 4,
    "weekGroup": "reis",
    "weekLabel": "Pilze & Reis"
  },
  {
    "name": "Röstiauflauf",
    "url": "roestiauflauf.html",
    "chapter": "Unsere Klassiker",
    "section": "Ofengerichte",
    "sectionRank": 7,
    "recipeRank": 5,
    "theme": "klassiker",
    "image": "images/roestiauflauf.webp",
    "searchText": "500 g Hähnchenbrust 1 kleine Dose Mais 1 kleine Dose Erbsen und Möhren 1 Becher Crème fraîche 1 Becher Crème fraîche Kräuter 1 Becher Sahne Nach Geschmack Salz, Pfeffer und Gewürze 1 Packung Röstiecken",
    "newRank": 42,
    "portions": 4,
    "weekGroup": "kartoffel",
    "weekLabel": "Kartoffelauflauf"
  },
  {
    "name": "Schaschlik-Gulasch",
    "url": "schaschlik-gulasch.html",
    "chapter": "Unsere Klassiker",
    "section": "Schmorgerichte",
    "sectionRank": 6,
    "recipeRank": 0,
    "theme": "schmor",
    "image": "images/schaschlik-gulasch.webp",
    "searchText": "400 g Hähnchen- oder Putenfleisch 120 g Paprika 80 g Zwiebeln 160 ml Schaschliksoße 80 ml Wasser",
    "newRank": 43,
    "portions": 4,
    "weekGroup": "reis",
    "weekLabel": "Fleisch & Gemüse"
  },
  {
    "name": "Spätzle in Hackfleisch-Bratensoße",
    "url": "spaetzle-in-hackbratensosse.html",
    "chapter": "Unsere Klassiker",
    "section": "Pfannen- & Hackgerichte",
    "sectionRank": 5,
    "recipeRank": 6,
    "theme": "pasta",
    "image": "images/spaetzle-in-hackbratensosse.webp",
    "searchText": "400 g Gemischtes Hackfleisch 500 g Frische Spätzle 2 Stk. Zwiebeln 2 Stk. Karotten 70 g Tomatenmark 2 EL Sojasoße 200 ml Rinderbrühe 2 EL Butter 1 Stk. Salatgurke 300 g Naturjoghurt 1 Päckchen Gewürzmischung „Gulaschgewürz“ Etwas Salz, Pfeffer und Zucker",
    "newRank": 44,
    "portions": 4,
    "weekGroup": "nudel",
    "weekLabel": "Spätzle & Gemüse"
  },
  {
    "name": "Spitzkohlsalat mit Pistazien",
    "url": "spitzkohlsalat-mit-pistazien.html",
    "chapter": "Was Kleines dazu",
    "section": "Salate",
    "sectionRank": 0,
    "recipeRank": 4,
    "theme": "beilagen",
    "image": "images/spitzkohlsalat-mit-pistazien.webp",
    "searchText": "1 Kopf Spitzkohl 1 Bund Radieschen 1–2 Stk. Rote Zwiebeln 1 Packung Pistazien, geschält 2 EL 7-Kräuter-Essig 3 EL Mayonnaise Etwas Salz und Pfeffer Nach Geschmack Dill",
    "newRank": 45
  },
  {
    "name": "Twoiback",
    "url": "twoiback-nach-mama-reimer.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 7,
    "theme": "suesses",
    "image": "images/twoiback-nach-mama-reimer.webp",
    "searchText": "500 ml Milch ½ Würfel Hefe 80 g Öl 750 g Mehl 1 Prise Zucker 1 EL Salz",
    "newRank": 46
  },
  {
    "name": "Ölbällchen",
    "url": "oelbaellchen.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 8,
    "theme": "suesses",
    "image": "images/oelbaellchen.webp",
    "searchText": "2 Pck. Trockenhefe (insgesamt 14 g) 125 ml Lauwarmes Wasser 60 g Feiner Zucker 450 g Weizenmehl, Type 405 1 Prise Salz 250 ml Lauwarme Milch 2 Eier, verquirlt 100 g Korinthen, optional 100 g Rosinen, optional 1 Säuerlicher Apfel, z. B. Granny Smith, optional Ca. 1,5 l Raps- oder Sonnenblumenöl zum Frittieren Nach Bedarf Puderzucker",
    "newRank": 47
  },
  {
    "name": "Neapolitanischer Pizzateig",
    "url": "neapolitanischer-pizzateig.html",
    "chapter": "Unsere Klassiker",
    "section": "Pizza",
    "sectionRank": 4,
    "recipeRank": 0,
    "theme": "pizza",
    "image": "images/neapolitanischer-pizzateig.webp",
    "searchText": "1 kg Weizenmehl, Type 00 640 ml Kaltes Wasser 3 g Frische Hefe, alternativ ca. 1 g Trockenhefe 30 g Feines Meersalz, ca. 5 TL Etwas Mehl oder feiner Hartweizengrieß zum Formen",
    "newRank": 48,
    "portions": 6,
    "weekGroup": "teig",
    "weekLabel": "Pizza"
  },
  {
    "name": "Knoblauchöl",
    "url": "knoblauchoel.html",
    "chapter": "Das macht den Unterschied",
    "section": "Würzöle & Butter",
    "sectionRank": 3,
    "recipeRank": 0,
    "theme": "sossen",
    "image": "images/knoblauchoel.webp",
    "searchText": "1 Knolle Knoblauch 250 ml Rapsöl, alternativ mildes Olivenöl ½ TL Salz",
    "newRank": 49
  },
  {
    "name": "Plov",
    "url": "plov-mit-putenoberkeule.html",
    "chapter": "Unsere Klassiker",
    "section": "Reisgerichte",
    "sectionRank": 1,
    "recipeRank": 0,
    "theme": "reisgerichte",
    "image": "images/plov-mit-putenoberkeule.webp",
    "searchText": "600 g Putenoberkeule, alternativ Rindernacken, Rinderschulter, Lammnacken oder Lammschulter 400 g Parboiled Langkornreis 500–550 g Karotten, gerne gelbe und orange 120 g Zwiebeln 1 Knolle Knoblauch 1–2 ganze Chilischoten 150 ml Raps- oder Sonnenblumenöl 1 ½ TL Kreuzkümmel, ganz 1 TL Koriandersaat, gestoßen Alternativ 2–3 TL Plovgewürz statt Kreuzkümmel und Koriandersaat 2 TL Salz, später nach Geschmack 1 Prise Zucker Ca. 700 ml heißes Wasser",
    "newRank": -1
  },
  {
    "name": "Tomatensalat zum Plov",
    "url": "tomatensalat-zum-plov.html",
    "chapter": "Was Kleines dazu",
    "section": "Salate",
    "sectionRank": 0,
    "recipeRank": 5,
    "theme": "beilagen",
    "image": "images/tomatensalat-zum-plov.webp",
    "searchText": "600 g reife, aromatische Tomaten 1 kleine Zwiebel 2 Frühlingszwiebeln Optional etwas milde rote Chili ½ TL Salz",
    "newRank": -2
  },
  {
    "name": "Walnussbrot",
    "url": "walnussbrot.html",
    "chapter": "Was Kleines dazu",
    "section": "Brot, Buns & Teiggebäck",
    "sectionRank": 2,
    "recipeRank": 4,
    "theme": "beilagen",
    "image": "images/walnussbrot.webp",
    "searchText": "480 g Weizenmehl Type 550 100 g Weizenmehl Type 1050 100 g Roggenmehl Type 1150 430 ml lauwarmes Wasser 10 g frische Hefe 15 g Salz 2 EL neutrales Öl 20 g Honig 130 g Walnüsse",
    "newRank": -3
  },
  {
    "name": "Deftige Gulaschsuppe",
    "url": "deftige-gulaschsuppe.html",
    "chapter": "Unsere Klassiker",
    "section": "Suppen",
    "sectionRank": 8,
    "recipeRank": 0,
    "theme": "suppen",
    "image": "images/deftige-gulaschsuppe.webp",
    "searchText": "500 g Rinderschulter oder Rindernacken 2 EL Butterschmalz 1 große Zwiebel, fein gewürfelt 2 Zehen Knoblauch, fein gehackt 1 EL Tomatenmark 150 ml Rotwein, nach Geschmack 800 ml Rinderbouillon 2 EL Zucker 3 EL Paprikapulver, edelsüß 3 TL Paprikapulver, rosenscharf 2 Lorbeerblätter 4 Zweige Majoran, Blätter grob gehackt 3 große Kartoffeln, gewürfelt 1 große Karotte, in Scheiben 2 Paprikaschoten, klein gewürfelt 250 g Champignons, in Scheiben; kleine Champignons geviertelt ½ Bund Petersilie, fein gehackt Nach Geschmack Salz und Pfeffer",
    "newRank": -4
  },
  {
    "name": "Fantakuchen mit Pfirsich",
    "url": "fantakuchen-mit-pfirsich.html",
    "chapter": "Was Süßes geht immer",
    "section": "Kuchen & Torten",
    "sectionRank": 1,
    "recipeRank": 0,
    "theme": "suesses",
    "image": "images/fantakuchen-mit-pfirsich.webp",
    "searchText": "4 Eier, Größe M 250 g Zucker 1 Pck. Vanillezucker 125 ml Speiseöl 150 ml Fanta oder eine andere Orangenlimonade 250 g Weizenmehl 3 gestr. TL Backpulver 2 Dosen Pfirsiche, je etwa 470 g Abtropfgewicht 600 ml Schlagsahne, gut gekühlt 3 Pck. Sahnesteif 5 Pck. Vanillezucker 500 g Schmand Nach Bedarf Zimtzucker",
    "newRank": -5
  },
  {
    "name": "Hähnchen Rouladen",
    "url": "haehnchenrouladen.html",
    "chapter": "Unsere Klassiker",
    "section": "Ofengerichte",
    "sectionRank": 7,
    "recipeRank": 1,
    "theme": "klassiker",
    "image": "images/haehnchenrouladen.webp",
    "searchText": "1 kg Hähnchenbrustfilet 1 Pck. Kochschinken 1 Pck. Gouda in Scheiben 3 Becher Schmand, je etwa 200 g 200 ml Sweet-Chili-Soße 200 ml Wasser 1 EL Gemüsebrühepulver Nach Geschmack Salz Nach Geschmack Pfeffer Nach Geschmack Paprikapulver, edelsüß",
    "newRank": -6
  },
  {
    "name": "Gesundes Müsli",
    "url": "gesundes-muesli-von-evelyn-w.html",
    "chapter": "Was Süßes geht immer",
    "section": "Frühstück & Müsli",
    "sectionRank": 0,
    "recipeRank": 0,
    "theme": "suesses",
    "image": "images/gesundes-muesli-von-evelyn-w.webp",
    "searchText": "500 g Weiche Haferflocken 80 g Roggenflocken 80 g Kokosflocken 120 g Mandeln, geschält 60 g Cashewkerne 80 g Sonnenblumenkerne 60 g Kürbiskerne 125 g Butter, zimmerwarm 200 g Akazienhonig Nach Geschmack Zimt",
    "newRank": -7
  },
  {
    "name": "Brokkoli Salat",
    "url": "brokkoli-salat.html",
    "chapter": "Was Kleines dazu",
    "section": "Salate",
    "sectionRank": 0,
    "recipeRank": 6,
    "theme": "beilagen",
    "image": "images/brokkoli-salat.webp",
    "searchText": "1 Brokkoli, in kleinen Röschen 250 g Cherrytomaten, halbiert 250 g Kernlose Weintrauben, halbiert 150 g Honig-Salz-Mandeln, fertig gekauft 4–5 EL Mayonnaise 1 Pck. Paprika-Salatkrönung 1 TL Zucker Nach Geschmack Salz und Pfeffer",
    "newRank": -8
  },
  {
    "name": "Rote Bete Salat",
    "url": "rote-bete-salat.html",
    "chapter": "Was Kleines dazu",
    "section": "Salate",
    "sectionRank": 0,
    "recipeRank": 7,
    "theme": "beilagen",
    "image": "images/rote-bete-salat.webp",
    "searchText": "500 g Gekochte Rote Bete, in dünnen Streifen 3 Möhren, frisch geraspelt 1 kleine Zwiebel, fein gewürfelt 4 EL Mayonnaise 2 EL Schmand Nach Geschmack Salz und Pfeffer 1 große Handvoll Kartoffelsticks",
    "newRank": -9
  },
  {
    "name": "Käsebrötchen",
    "url": "kaesebroetchen.html",
    "chapter": "Was Kleines dazu",
    "section": "Brot, Buns & Teiggebäck",
    "sectionRank": 2,
    "recipeRank": 0,
    "theme": "beilagen",
    "image": "images/kaesebroetchen.webp",
    "searchText": "320 ml Milch, lauwarm ½ Würfel Frische Hefe 1 EL Zucker 100 ml Neutrales Speiseöl ½ EL Salz Ca. 500 g Mehl 1 Ei 2 EL Milch 1 Prise Salz Nach Bedarf Geriebener Käse",
    "newRank": -10
  },
  {
    "name": "Cookies",
    "url": "cookies.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 1,
    "theme": "suesses",
    "image": "images/cookies.webp",
    "searchText": "150 g Butter, weich 150 g Rohrzucker ½ TL Gemahlene Vanille oder Vanillepaste 1 Ei 200 g Mehl ½ TL Backpulver 1 Prise Salz 100 g Haselnüsse oder Mandeln, gehackt 150 g Zartbitterschokolade, gehackt oder als Schoko-Chunks",
    "newRank": -11
  },
  {
    "name": "Macarons",
    "url": "macarons.html",
    "chapter": "Was Süßes geht immer",
    "section": "Gebäck & süße Teilchen",
    "sectionRank": 2,
    "recipeRank": 0,
    "theme": "suesses",
    "image": "images/macarons.webp",
    "searchText": "50 g Eiweiß, etwa 2 Eier 52 g Zucker 70 g Gemahlene Mandeln, fein gesiebt 62 g Puderzucker 100 g Weiße Schokolade 50 g Fruchtpüree, zum Beispiel Himbeere, Mango oder Passionsfrucht 25 g Schlagsahne Optional Etwas Frischkäse",
    "newRank": -12
  },
  {
    "name": "Lauch Creme Kuchen",
    "url": "lauch-creme-kuchen.html",
    "chapter": "Unsere Klassiker",
    "section": "Ofengerichte",
    "sectionRank": 7,
    "recipeRank": 0,
    "theme": "klassiker",
    "image": "images/lauch-creme-kuchen.webp",
    "searchText": "500 g Hähnchenbrustfilet 750 g Porree (Lauch) 200 g Bacon (Frühstücksspeck) 2–3 EL Speiseöl, zum Beispiel Olivenöl 50 g Butter oder Margarine 50 g Weizenmehl 500 ml Milch Nach Geschmack Salz Nach Geschmack Schwarzer Pfeffer, frisch gemahlen Nach Geschmack Muskatnuss, frisch gerieben 400 g Weizenmehl 4 gestr. TL Backpulver 150 g Joghurt 100 ml Speiseöl, zum Beispiel Olivenöl 1 Ei, Größe M 1 TL Salz 100 g Rotes Pesto Etwas Fett für das Backblech",
    "newRank": -13
  }
];
